<a href="https://colab.research.google.com/github/Malleshcr7/AI-ML-Projects/blob/main/NumPy_Basics_to_Advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
                                                 #Creating an Array

In [ ]:
import numpy as np

py_list = [1, 2, 3, 4 ,5]
np_array = np.array(py_list)

print(f"List of numbers: {py_list}")
print(f"Numpy array: {np_array}")
print(f"Type of list: {type(py_list)}")
print(f"Type of numpy array: {type(np_array)}")

List of numbers: [1, 2, 3, 4, 5]
Numpy array: [1 2 3 4 5]
Type of list: <class 'list'>
Type of numpy array: <class 'numpy.ndarray'>


In [ ]:
py_twodarray = [[1, 2, 3], [4, 5, 6]]
nu_array = np.array(py_twodarray)
print(f"2D array: {nu_array}")

2D array: [[1 2 3]
 [4 5 6]]


In [ ]:
                                               #Anatomy of a NumPy Array

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Dimensions of arrasy{matrix.ndim}")
print(f"Size of array{matrix.size}")
print(f"Shape of array{matrix.shape}")
print(f"Type of array{matrix.dtype}")
print("\nA 2D NumPy array (matrix):\n", matrix)

Dimensions of arrasy2
Size of array6
Shape of array(2, 3)
Type of arrayint64

A 2D NumPy array (matrix):
 [[1 2 3]
 [4 5 6]]


In [ ]:
                                                  #Creating Arrays from Scratch